export const ROUTES_PATHS = {
  AUTH: {
    DEFAULT: "auth",
    LOGIN: "login",
    SELLO: "sello",
    CLAVE: "clave",
  },

  GENERAR: {
    DEFAULT: "generar",
    CLAVE_INTERNET: "clave-internet",
    CLAVE_OLVIDE: "olvide-clave",
    SELLO: "sello",
    CLAVE_CAMBIAR_TEMP: "cambiar-clave-temporal",
  },
  
  MAIN: {
    DEFAULT: "main",
    CONSULTAS: "consultas",
    PAGOS: "pagos",
    TRANSFERENCIA: "transferencias",
    PAGOS_SERVICIOS: "pagos-servicios",
  }
}

export const INTER_PATHS = {
  // AUTH
  AUTH_DEFAULT: `${ROUTES_PATHS.AUTH.DEFAULT}`,
  AUTH_LOGIN: `${ROUTES_PATHS.AUTH.LOGIN}`,
  AUTH_SELLO: `${ROUTES_PATHS.AUTH.SELLO}`,
  AUTH_CLAVE: `${ROUTES_PATHS.AUTH.CLAVE}`,
  // AUHT - GENERAR
  GENERAR_DEFAULT: `${ROUTES_PATHS.GENERAR.DEFAULT}`,
  GENERAR_CLAVE_INTERNET: `${ROUTES_PATHS.GENERAR.CLAVE_INTERNET}`,
  GENERAR_CLAVE_OLVIDE: `${ROUTES_PATHS.GENERAR.CLAVE_OLVIDE}`,
  GENERAR_SELLO: `${ROUTES_PATHS.GENERAR.SELLO}`,
  GENERAR_CLAVE_CAMBIAR_TEMP: `${ROUTES_PATHS.GENERAR.CLAVE_CAMBIAR_TEMP}`,
  // MAIN
  MAIN_DEFAULT: `${ROUTES_PATHS.MAIN.DEFAULT}`,
  MAIN_CONSULTAS: `${ROUTES_PATHS.MAIN.CONSULTAS}`,
  MAIN_PAGOS: `${ROUTES_PATHS.MAIN.PAGOS}`,
  MAIN_TRANSFERENCIA: `${ROUTES_PATHS.MAIN.TRANSFERENCIA}`,
  MAIN_PAGOS_SERVICIOS: `${ROUTES_PATHS.MAIN.PAGOS_SERVICIOS}`,

}

export const INTER_ROUTES = {
  // AUTH
  AUTH: `/${INTER_PATHS.AUTH_DEFAULT}`,
  AUTH_LOGIN: `/${INTER_PATHS.AUTH_DEFAULT}/${INTER_PATHS.AUTH_LOGIN}`,
  AUTH_SELLO: `/${INTER_PATHS.AUTH_DEFAULT}/${INTER_PATHS.AUTH_SELLO}`,
  AUTH_CLAVE: `/${INTER_PATHS.AUTH_DEFAULT}/${INTER_PATHS.AUTH_CLAVE}`,

  // AUTH - GENERAR
  GENERAR_CLAVE_INTERNET: `/${INTER_PATHS.AUTH_DEFAULT}/${INTER_PATHS.GENERAR_DEFAULT}/${INTER_PATHS.GENERAR_CLAVE_INTERNET}`,
  GENERAR_CLAVE_OLVIDO: `/${INTER_PATHS.AUTH_DEFAULT}/${INTER_PATHS.GENERAR_DEFAULT}/${INTER_PATHS.GENERAR_CLAVE_OLVIDE}`,
  GENERAR_CLAVE_CAMBIAR_TEMP: `/${INTER_PATHS.AUTH_DEFAULT}/${INTER_PATHS.GENERAR_DEFAULT}/${INTER_PATHS.GENERAR_CLAVE_CAMBIAR_TEMP}`,
  GENERAR_SELLO: `/${INTER_PATHS.AUTH_DEFAULT}/${INTER_PATHS.GENERAR_DEFAULT}/${INTER_PATHS.GENERAR_SELLO}`,
  
  // MAIN
  MAIN: `/${INTER_PATHS.MAIN_DEFAULT}`,
  MAIN_CONSULTAS: `/${INTER_PATHS.MAIN_DEFAULT}/${INTER_PATHS.MAIN_CONSULTAS}`,
  MAIN_PAGOS: `/${INTER_PATHS.MAIN_DEFAULT}/${INTER_PATHS.MAIN_PAGOS}`,
  MAIN_TRANSFERENCIA: `/${INTER_PATHS.MAIN_DEFAULT}/${INTER_PATHS.MAIN_TRANSFERENCIA}`,
  MAIN_PAGOS_SERVICIOS: `/${INTER_PATHS.MAIN_DEFAULT}/${INTER_PATHS.MAIN_PAGOS_SERVICIOS}`,
}
