export const ROUTES_PATHS = {
  AUTH: {
    DEFAULT: "auth",
    LOGIN: "login",
    SELLO: "sello",
    CLAVE: "clave",
  },

  GENERAR: {
    DEFAULT: "generar",
    CLAVE_INTERNET: "clave-internet",
    CLAVE_OLVIDE: "olvide-clave",
    SELLO: "sello",
    CLAVE_CAMBIAR_TEMP: "cambiar-clave-temporal",
  },

  MAIN: {
    DEFAULT: "main",
    
    CONSULTAS: "consultas",

    PAGOS: {
      DEFAULT: "pagos",
      RECARGAS: "recargas",
      CREDITO_TARJETA: "tarjeta-credito",
      CREDITO_PROPIO: "creditos-propios",
      CREDITO_TERCERO: "creditos-terceros",
    },

    TRANSFERENCIA: {
      DEFAULT: "transferencias",
      CUENTA_PROPIA: "cuentas-propias",
      CUENTA_TERCEROS: "cuentas-terceros",
      CUENTA_OTRO_BAMCO: "cuentas-otros-bancos",
      ENVIAR_GIRO: "enviar-giro",
    },

    PAGOS_SERVICIOS: {
      DEFAULT: "pagos-servicios",
      LUZ: "luz",
      AGUA: "agua",
      EMPRESA_INSTITUCION: "empresas-instituciones",
      UNIVERSIDAD: "universidades",
    },
  },
}

export const INTER_PATHS = {
  // AUTH
  AUTH_DEFAULT: `${ROUTES_PATHS.AUTH.DEFAULT}`,
  AUTH_LOGIN: `${ROUTES_PATHS.AUTH.LOGIN}`,
  AUTH_SELLO: `${ROUTES_PATHS.AUTH.SELLO}`,
  AUTH_CLAVE: `${ROUTES_PATHS.AUTH.CLAVE}`,
  // AUHT - GENERAR
  GENERAR_DEFAULT: `${ROUTES_PATHS.GENERAR.DEFAULT}`,
  GENERAR_CLAVE_INTERNET: `${ROUTES_PATHS.GENERAR.CLAVE_INTERNET}`,
  GENERAR_CLAVE_OLVIDE: `${ROUTES_PATHS.GENERAR.CLAVE_OLVIDE}`,
  GENERAR_SELLO: `${ROUTES_PATHS.GENERAR.SELLO}`,
  GENERAR_CLAVE_CAMBIAR_TEMP: `${ROUTES_PATHS.GENERAR.CLAVE_CAMBIAR_TEMP}`,

  // MAIN
  MAIN_DEFAULT: `${ROUTES_PATHS.MAIN.DEFAULT}`,
  MAIN_CONSULTAS: `${ROUTES_PATHS.MAIN.CONSULTAS}`,
  MAIN_PAGOS: `${ROUTES_PATHS.MAIN.PAGOS.DEFAULT}`,
  MAIN_TRANSFERENCIA: `${ROUTES_PATHS.MAIN.TRANSFERENCIA.DEFAULT}`,
  MAIN_PAGOS_SERVICIOS: `${ROUTES_PATHS.MAIN.PAGOS_SERVICIOS.DEFAULT}`,

  // MAIN - PAGOS
  PAGO_RECARGA: `${ROUTES_PATHS.MAIN.PAGOS.RECARGAS}`,
  PAGO_CREDITO_TARJETA: `${ROUTES_PATHS.MAIN.PAGOS.CREDITO_TARJETA}`,
  PAGO_CREDITO_PROPIO: `${ROUTES_PATHS.MAIN.PAGOS.CREDITO_PROPIO}`,
  PAGO_CREDITO_TERCERO: `${ROUTES_PATHS.MAIN.PAGOS.CREDITO_TERCERO}`,

  // MAIN - PAGOS SERVICIOS
  PAGOSEV_LUZ: `${ROUTES_PATHS.MAIN.PAGOS_SERVICIOS.LUZ}`,
  PAGOSEV_AGUA: `${ROUTES_PATHS.MAIN.PAGOS_SERVICIOS.AGUA}`,
  PAGOSEV_EMPRESA_INST: `${ROUTES_PATHS.MAIN.PAGOS_SERVICIOS.EMPRESA_INSTITUCION}`,
  PAGOSEV_UNIVERSIDAD: `${ROUTES_PATHS.MAIN.PAGOS_SERVICIOS.UNIVERSIDAD}`,

  // MAIN - TRANSFERENCIAS
  TRAN_CUENTA_PROPIA: `${ROUTES_PATHS.MAIN.TRANSFERENCIA.CUENTA_PROPIA}`,
  TRAN_CUENTA_TERCERO: `${ROUTES_PATHS.MAIN.TRANSFERENCIA.CUENTA_TERCEROS}`,
  TRAN_CUENTA_OTRO_BAMCO: `${ROUTES_PATHS.MAIN.TRANSFERENCIA.CUENTA_OTRO_BAMCO}`,
  TRAN_ENVIAR_GIRO: `${ROUTES_PATHS.MAIN.TRANSFERENCIA.ENVIAR_GIRO}`,

}

export const INTER_ROUTES = {
  // AUTH
  AUTH: `/${INTER_PATHS.AUTH_DEFAULT}`,
  AUTH_LOGIN: `/${INTER_PATHS.AUTH_DEFAULT}/${INTER_PATHS.AUTH_LOGIN}`,
  AUTH_SELLO: `/${INTER_PATHS.AUTH_DEFAULT}/${INTER_PATHS.AUTH_SELLO}`,
  AUTH_CLAVE: `/${INTER_PATHS.AUTH_DEFAULT}/${INTER_PATHS.AUTH_CLAVE}`,

  // AUTH - GENERAR
  GENERAR_CLAVE_INTERNET: `/${INTER_PATHS.AUTH_DEFAULT}/${INTER_PATHS.GENERAR_DEFAULT}/${INTER_PATHS.GENERAR_CLAVE_INTERNET}`,
  GENERAR_CLAVE_OLVIDO: `/${INTER_PATHS.AUTH_DEFAULT}/${INTER_PATHS.GENERAR_DEFAULT}/${INTER_PATHS.GENERAR_CLAVE_OLVIDE}`,
  GENERAR_CLAVE_CAMBIAR_TEMP: `/${INTER_PATHS.AUTH_DEFAULT}/${INTER_PATHS.GENERAR_DEFAULT}/${INTER_PATHS.GENERAR_CLAVE_CAMBIAR_TEMP}`,
  GENERAR_SELLO: `/${INTER_PATHS.AUTH_DEFAULT}/${INTER_PATHS.GENERAR_DEFAULT}/${INTER_PATHS.GENERAR_SELLO}`,

  // MAIN
  MAIN: `/${INTER_PATHS.MAIN_DEFAULT}`,
  MAIN_CONSULTAS: `/${INTER_PATHS.MAIN_DEFAULT}/${INTER_PATHS.MAIN_CONSULTAS}`,
  MAIN_PAGOS: `/${INTER_PATHS.MAIN_DEFAULT}/${INTER_PATHS.MAIN_PAGOS}`,
  MAIN_TRANSFERENCIA: `/${INTER_PATHS.MAIN_DEFAULT}/${INTER_PATHS.MAIN_TRANSFERENCIA}`,
  MAIN_PAGOS_SERVICIOS: `/${INTER_PATHS.MAIN_DEFAULT}/${INTER_PATHS.MAIN_PAGOS_SERVICIOS}`,

  // MAIN - PAGOS
  PAGO_RECARGA: `/${INTER_PATHS.MAIN_DEFAULT}/${INTER_PATHS.MAIN_PAGOS}/${INTER_PATHS.PAGO_RECARGA}`,
  PAGO_CREDITO_TARJETA: `/${INTER_PATHS.MAIN_DEFAULT}/${INTER_PATHS.MAIN_PAGOS}/${INTER_PATHS.PAGO_CREDITO_TARJETA}`,
  PAGO_CREDITO_PROPIO: `/${INTER_PATHS.MAIN_DEFAULT}/${INTER_PATHS.MAIN_PAGOS}/${INTER_PATHS.PAGO_CREDITO_PROPIO}`,
  PAGO_CREDITO_TERCERO: `/${INTER_PATHS.MAIN_DEFAULT}/${INTER_PATHS.MAIN_PAGOS}/${INTER_PATHS.PAGO_CREDITO_TERCERO}`,

  // MAIN - PAGOS SERVICIOS
  PAGOSEV_LUZ: `/${INTER_PATHS.MAIN_DEFAULT}/${INTER_PATHS.MAIN_PAGOS_SERVICIOS}/${INTER_PATHS.PAGOSEV_LUZ}`,
  PAGOSEV_AGUA: `/${INTER_PATHS.MAIN_DEFAULT}/${INTER_PATHS.MAIN_PAGOS_SERVICIOS}/${INTER_PATHS.PAGOSEV_AGUA}`,
  PAGOSEV_EMPRESA_INST: `/${INTER_PATHS.MAIN_DEFAULT}/${INTER_PATHS.MAIN_PAGOS_SERVICIOS}/${INTER_PATHS.PAGOSEV_EMPRESA_INST}`,
  PAGOSEV_UNIVERSIDAD: `/${INTER_PATHS.MAIN_DEFAULT}/${INTER_PATHS.MAIN_PAGOS_SERVICIOS}/${INTER_PATHS.PAGOSEV_UNIVERSIDAD}`,

  // MAIN - TRANSFERENCIAS
  TRAN_CUENTA_PROPIA: `/${INTER_PATHS.MAIN_DEFAULT}/${INTER_PATHS.MAIN_TRANSFERENCIA}/${INTER_PATHS.TRAN_CUENTA_PROPIA}`,
  TRAN_CUENTA_TERCERO: `/${INTER_PATHS.MAIN_DEFAULT}/${INTER_PATHS.MAIN_TRANSFERENCIA}/${INTER_PATHS.TRAN_CUENTA_TERCERO}`,
  TRAN_CUENTA_OTRO_BAMCO: `/${INTER_PATHS.MAIN_DEFAULT}/${INTER_PATHS.MAIN_TRANSFERENCIA}/${INTER_PATHS.TRAN_CUENTA_OTRO_BAMCO}`,
  TRAN_ENVIAR_GIRO: `/${INTER_PATHS.MAIN_DEFAULT}/${INTER_PATHS.MAIN_TRANSFERENCIA}/${INTER_PATHS.TRAN_ENVIAR_GIRO}`,
}
